name: 'Install dependencies'
description: 'Prepare repository and all dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.5'

    - name: Install dependencies
      shell: bash
      run: bun install
