name: Prerelease
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - run: bunx pkg-pr-new publish --bun
